# ── Módulo de usuarios (sin cambios) ─────────────────────────────────
api.usuarios.url=http://192.168.137.74:8087

# ── RabbitMQ compartido — CloudAMQP ──────────────────────────────────
spring.rabbitmq.host=chimpanzee.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=kqmqkvys
spring.rabbitmq.password=ONxkp3IxL4gaZX5eqDqzivLOWaHaV5-M
spring.rabbitmq.virtual-host=kqmqkvys