# ========================================
# CONFIGURACIÓN GENERAL DEL PERFIL
# ========================================
# Define que estoy trabajando en el entorno de desarrollo local (dev)
spring.profiles.active=dev
spring.application.name=ga-ms-restaurante

# ========================================
# CONFIGURACIÓN DEL SERVIDOR
# ========================================
# El backend de Restaurante se ejecutará en el puerto local 8080 de Windows
server.port=8080

# ========================================
# CONEXIÓN CON EL MICROSERVICIO DE USUARIOS
# ========================================
# Esta es la ruta que usará mi código para buscar el módulo de usuarios.
# Apunta directamente a la IP de la Máquina Virtual de Ubuntu en el puerto 8081.
api.usuarios.url=http://10.0.2.15:8081

# ========================================
# BASE DE DATOS LOCAL (H2 EN MEMORIA)
# ========================================
# Base de datos rápida y temporal para desarrollo (se limpia al apagar la app)
spring.datasource.url=jdbc:h2:mem:ga-ms-restaurante_db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ========================================
# ddl-auto=create-drop: Crea las tablas de restaurante al iniciar y las borra al salir
spring.jpa.hibernate.ddl-auto=create-drop

# Muestra y formatea las consultas de base de datos en la consola para revisar tu lógica
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# CONSOLA VISUAL DE LA BASE DE DATOS (H2)
# ========================================
# Te permite entrar desde el navegador a ver tus tablas en: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========================================
# CONFIGURACIÓN DE CORREO / MENSAJERÍA (RABBITMQ)
# ========================================
# Configuración base para el servicio de mensajería asíncrona local
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ========================================
# DOCUMENTACIÓN DE ENDPOINTS (SWAGGER)
# ========================================
# Panel visual para probar las rutas en: http://localhost:8080/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true


# Configuraciones de ga-lib-security
security.secret=R2FzdHJvU2VuYTIwMjZTdXBlclNlY3JldEtleTEyMzQ1Ng==
security.expiration-ms=86400000

# Hay que agregar segun como esta en GitLab